config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  # post "/users/1/answers" => "answers#create", as: "random_answer"
  # post '/users/:user_id/answers', to: 'answers#create', as: 'random_answer'

  resources :answers
  resources :questions do
    resources :answers
  end
  resources :subjects do
    resources :questions
  end
  resources :users do
      resources :answers
  end

  resources :users
  resource  :session


end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  # AM: +1 validations. I would organize so that associations and validations are grouped into their own section. Helps readability.
  validates :question, presence: :true
  validates :body, presence: :true
  belongs_to :user
  validates :user, presence: :true
  belongs_to :subjects
end

app/models/question.rb
class Question < ActiveRecord::Base
  # serialize :question_text
  belongs_to :subject
  has_many :answers, dependent: :destroy
  validates :question_text, presence: :true
  belongs_to :user
  # validates :user, presence: :true

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  # serialize :name
  has_many :questions, dependent: :destroy
  validates :name, presence: :true
  has_many :answers, through: :questions
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :subjects
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # index
  def index
    @answers = Answer.all
  end

  # new
  def new
    # AM: +1
    redirect_to root_path unless @current_user
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  # create
  def create
    # AM: I see you use this multiple times. Could you use something like `before_action` to make your controller more DRY?
    redirect_to root_path unless @current_user
    @question = Question.find(params[:question_id])
    subject_id = @question.subject_id
    @answer = @question.answers.new(answer_params)
    @answer.subject_id = subject_id
    @answer.user = @current_user
    @answer.save

    redirect_to @answer
  end

  #show
  def show
    @answer = Answer.find(params[:id])
  end

  # edit
  def edit
    redirect_to root_path unless @current_user
    @answer = Answer.find(params[:id])
  end


  # update
  def update
    redirect_to root_path unless @current_user
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)

    redirect_to @answer
  end

  # destroy
  def destroy
    redirect_to root_path unless @current_user
    @answer = Answer.find(params[:id])
    @answer.destroy

    redirect_to answers_path
  end

  private
  def answer_params
    # AM: Do you need to pass in a `subject_id` through `answer_params` or is that something you can access via the question an answer belongs to?
    params.require(:answer).permit(:body, :subject_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_current_user

  helper_method :random_question

  def get_current_user
    if User.exists?(session[:user_id])
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def random_question

  #  subject1 = Subject.find(1)
  #  get_random_question = subject1.questions.sample
   get_random_question = Question.all.sample
   @question = get_random_question

   answer_user_id_array = @question.answers.collect(&:user_id)

   if answer_user_id_array.include? @current_user.id
    #  subject1 = Subject.find(1)
    #  get_random_question = subject1.questions.sample
     get_random_question = Question.all.sample
     @question = get_random_question
   else
   end
    @question
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # index
  def index
    @questions = Question.all
  end

  # new
  def new
    redirect_to root_path unless @current_user
    if @subject == nil
      @question = Question.new
    end
    else
      @subject = Subject.find(params[:subject_id])
      @question = @subject.questions.new
    end


  # create
  def create
    redirect_to root_path unless @current_user
    @subject = Subject.find(params[:subject_id])
    @question = @subject.questions.new(question_params)
    @question.user = @current_user
    @question.save

    redirect_to @question
  end

  #show
  def show
    @question = Question.find(params[:id])
  end

  # edit
  def edit
    redirect_to root_path unless @current_user
    @question = Question.find(params[:id])
  end

  # update
  def update
    redirect_to root_path unless @current_user
    @question = Question.find(params[:id])
    @question.update(question_params)

    redirect_to @question
  end

  # destroy
  def destroy
    redirect_to root_path unless @current_user
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:question_text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    @user.email = cookies[:email]
  end

  def create
    input_email = params[:user][:email]
    if User.exists?(email: input_email)
      @user = User.find_by(email: input_email)
      if @user.password === params[:user][:encrypted_password]
        session[:user_id] = @user.id
        cookies[:email] = @user.email
        redirect_to @user
      else
        flash[:alert] = "Wrong password!"
        redirect_to new_session_path
      end
    else
      flash[:alert] = "That user doesn't exist!"
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # index
  def index
    @subjects = Subject.all
  end

  # new
  def new
    redirect_to root_path unless @current_user
    @subject = Subject.new
  end

  # create
  def create
    redirect_to root_path unless @current_user
    @subject = Subject.new(subject_params)
    @subject.user = @current_user
    @subject.save
    # subject_id = @subject.subject_id
    # @subject.subject_id = subject_id

    redirect_to @subject
  end

  #show
  def show
    @subject = Subject.find(params[:id])
  end

  # edit
  def edit
    redirect_to root_path unless @current_user
    @subject = Subject.find(params[:id])
  end

  # update
  def update
    redirect_to root_path unless @current_user
    @subject = Subject.find(params[:id])
    @subject.update(subject_params)

    redirect_to @subject
  end

  # destroy
  def destroy
    redirect_to root_path unless @current_user
    @subject = Subject.find(params[:id])
    @subject.destroy

    redirect_to subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :random_question

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
  end

  def update
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/edit.html.erb
<h2>Edit Answer</h2>
  <%= form_for @answer do |f| %>
    <%= f.text_field :body %>
    <%= f.submit %>
  <% end %>
  <%= link_to "Delete Answer", @answer, method: :delete, class: 'btn btn-mini btn-danger' %>

app/views/answers/index.html.erb
<h2>All Submitted Answers</h2>
<% Subject.find_each do |subject_id| %>
  <ul>
    <h4><%= link_to subject_id.name, subject_id %></h4>
    <ul>
      <% Answer.where(subject_id: subject_id).find_each do |answer| %>
        <li>
          <%= link_to answer.body, answer %>
        </li>
      <% end %>
    </ul>
  </ul>
<% end %>
<h3><%= @current_user.username + "'s Submitted Answers" if @current_user %></h3>
<ul>
  <% @current_user.answers.find_each do |answer| %>
    <li>
      <%= link_to answer.body, answer %>
    </li>
  <% end %>
</ul>

app/views/answers/new.html.erb
<h2><%= @question.subject.name %></h2>
<ul>
<h3><%= @question.question_text %></h3>
</ul>
<%= form_for [@question, @answer] do |f| %>
  <%= f.text_field :body %>

  <%= f.submit "Submit Answer"%>
<% end %>

app/views/answers/show.html.erb
<h2>Question:</h2>
  <ul>
    <% question_id = @answer.question_id %>
    <% question_find = Question.find(question_id) %>
    <h3><%= question_find.question_text %><h3>
  </ul>
<h3>Answer:</h3>
  <ul>
    <%= @answer.body %>
    <%= link_to "Edit", edit_answer_path(@answer), class: 'btn btn-mini btn-success' if @current_user %>
    <%= link_to "Delete", @answer, method: :delete, class: 'btn btn-mini btn-danger' if @current_user %>
  </ul>
<h5>Submitted by <%= link_to @answer.user.username, @answer.user %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slips 2.0</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <% if @current_user %>
        <h1><%= link_to "Slips 2.0", @current_user %></h1>
        <% else %>
        <h1><%= link_to "Slips 2.0", root_path %></h1>
        <% end %>
        <% if @current_user %>
        <li><%= link_to "Welcome, #{@current_user.username}!", user_path(@current_user) if @current_user %></li>
        <li><%= link_to "Sign Out", session_path, method: :delete if @current_user %></li>
        <li><%= link_to "Subjects", subjects_path %></li>
        <li><%= link_to "Questions", questions_path %></li>
        <li><%= link_to "Answers", answers_path %></li>
        <li><%= link_to "Users", users_path %></li>
      </ul>
      <% else %>
      <% end %>
      <% flash.each do |type, message| %>
        <p class="<%= type %>"><%= message %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>

<%= form_for @question do |f| %>
  <%= f.text_field :question_text %>

  <%= f.submit %>
<% end %>

<%= link_to "Delete Question", @question, method: :delete, class: 'btn btn-mini btn-danger' %>

app/views/questions/index.html.erb
<h2>All Questions</h2>
<% Subject.find_each do |subject_id| %>
  <ul>
    <h3><%= link_to subject_id.name, subject_id %></h3>
    <ul>
      <% Question.where(subject_id: subject_id).find_each do |question| %>
        <li>
          <%= link_to question.question_text, question %>
        </li>
      <% end %>
    </ul>
  </ul>
<% end %>
<h3><%= @current_user.username + "'s Submitted Questions" %></h3>
<ul>
  <% @current_user.questions.find_each do |question| %>
    <li>
      <%= link_to question.question_text, question %>
    </li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h2>New Question for <%= link_to @subject.name, @subject %></h2>

  <%= form_for [@subject, @question] do |f| %>
    <%= f.text_field :question_text %>

    <%= f.submit %>
  <% end %>

app/views/questions/show.html.erb
<h2><%= @question.subject.name %></h2>
<ul>
<h3><%= @question.question_text %></h3>
</ul>
  <%= link_to "Answer", new_question_answer_path(@question), class: 'btn' if @current_user %>
<br>
<br>
<h3>Submitted Answers</h3>
<ul>
  <% @question.answers.each do |answer| %>
    <li><%= link_to "#{answer.body}", answer %></li>
    <h5>Submitted by <%= link_to answer.user.username, answer.user %></h5>
  <% end %>
</ul>

app/views/subjects/edit.html.erb
<h2>Edit Subject</h2>

<%= form_for @subject do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

<%= link_to "Delete", @subject, method: :delete, class: "delete" %>

app/views/subjects/index.html.erb
<h2>All Subjects <%= link_to "Add Subject", new_subject_path, class: 'btn btn-mini' if @current_user %></h2>
<ul>
  <% @subjects.each do |subject| %>
    <li>
      <%= link_to subject.name, subject %>
    </li>
  <% end %>
</ul>
<h3><%= @current_user.username + "'s Submitted Subjects" if @current_user %></h3>
<ul>
  <% @current_user.subjects.find_each do |subject| %>
    <li>
      <%= link_to subject.name, subject %>
    </li>
  <% end %>
</ul>

app/views/subjects/new.html.erb
<h2>New Subject</h2>

<%= form_for @subject do |f| %>
  <%= f.text_field :name %>

  <%= f.submit "Submit"%>
<% end %>

app/views/subjects/show.html.erb
<h2><%= @subject.name %></h2>

<h3>Questions <%= link_to "Add Question", new_subject_question_path(@subject), class: 'btn btn-mini' if @current_user %></h3>

<ul>
  <% @subject.questions.each do |question| %>
    <li><%= link_to "#{question.question_text}", question %></li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Submit" %>
<% end %>

app/views/users/index.html.erb
<h2>Users</h2>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.email, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :encrypted_password %>

  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<% @question = random_question %>

  <!-- <h2><%= @current_user.username %></h2> -->
  <h2><%= @question.subject.name %></h2>
  <ul>
  <h3><%= @question.question_text %></h3>
  </ul>
  <%= link_to "Answer", new_question_answer_path(@question), class: 'btn' if @current_user %>